export const VEHICLE_COLUMN_MAP: [string, string][] = [
  ['Plate No', 'plate_no'],
  ['Vehicle License Expiry Date', 'vehicle_license_expiry_date'],
  ['Branded', 'branded'],
  ['CID Permit Expiry', 'cid_permit_expiry'],
  ['Advertisement Permit Expiry', 'advertisement_permit_expiry'],
  ['Renewal Status', 'renewal_status'],
  ['Purchase Condition', 'purchase_condition'],
  ['Owner', 'owner'],
  ['Driver', 'driver'],
  ['Department', 'department'],
  ['Tyre Size', 'tyre_size'],
  ['Brand', 'brand'],
  ['Type of Car', 'type_of_car'],
  ['Fuel Type', 'fuel_type'],
  ['Seats', 'seats'],
  ['Chassis No', 'chassis_no'],
  ['Registration Date', 'registration_date'],
  ['Model', 'model'],
  ['Vehicle Condition', 'vehicle_condition'],
  ['Gear Type', 'gear_type'],
  ['Warranty Year/KM', 'warranty_year_km'],
  ['Free Service', 'free_service'],
  ['Last Service Mileage (KM)', 'last_service_mileage_km'],
  ['Remarks', 'remarks'],
  ['Upload Mulkiya', 'upload_mulkiya'],
  ['Upload Photos/Documents', 'upload_photos_documents'],
  ['Start Date of Instalments', 'start_date_of_instalments'],
  ['Instalment in Months', 'instalment_in_months'],
  ['Monthly Repayment', 'monthly_repayment'],
  ['Flat Rate', 'flat_rate'],
  ['End Date of Instalments', 'end_date_of_instalments'],
  ['Instalment in Years', 'instalment_in_years'],
  ['Finance Amount', 'finance_amount'],
  ['EMI Status', 'emi_status'],
  ['ID', 'source_id'],
  ['CID Permit Start', 'cid_permit_start'],
  ['Advertisement Permit Start', 'advertisement_permit_start'],
];

export const EXPENSE_COLUMN_MAP: [string, string][] = [
  ['Supplier Name', 'supplier_name'],
  ['Date', 'date'],
  ['Job Status (If Applicable)', 'job_status'],
  ['Payment Terms', 'payment_terms'],
  ['Type of Expense', 'type_of_expense'],
  ['Expense', 'expense'],
  ['Expense Description', 'expense_description'],
  ['Cost', 'cost'],
  ['Quotation Number', 'quotation_number'],
  ['Quotation', 'quotation_file'],
  ['Invoice Number', 'invoice_number'],
  ['Invoice', 'invoice_file'],
  ['Vehicle Number (If Applicable)', 'raw_vehicle_number_text'],
  ['Oryx Employees (If Applicable)', 'oryx_employees'],
  ['Teams (If Applicable)', 'teams'],
  ['Other Attachments (If Applicable)', 'other_attachments'],
  ['Requested By', 'requested_by'],
  ['Approved/Rejected By', 'approved_rejected_by'],
  ['Approval Date', 'approval_date'],
  ['Paid By', 'paid_by'],
  ['Payment Date', 'payment_date'],
  ['Grouped Expense Reference (If Petty Cash)', 'grouped_expense_reference'],
];
